//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelHub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basket
    {
        public string Login { get; set; }
        public Nullable<int> idRoom { get; set; }
        public Nullable<decimal> Price1day { get; set; }
        public Nullable<System.DateTime> DateBook { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public int idBasket { get; set; }
    
        public virtual LUJO_BODRUM LUJO_BODRUM { get; set; }
        public virtual MAXX_ROYAL_BELEK_GOLF_RESORT MAXX_ROYAL_BELEK_GOLF_RESORT { get; set; }
        public virtual STEIGENBERGER_ALCAZAR STEIGENBERGER_ALCAZAR { get; set; }
        public virtual Users Users { get; set; }
        public virtual VOYAGE_SORGUN VOYAGE_SORGUN { get; set; }
    }
}
