//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelHub
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TravelHubEntities : DbContext
    {
        public TravelHubEntities()
            : base("name=TravelHubEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Basket> Basket { get; set; }
        public virtual DbSet<Hotels> Hotels { get; set; }
        public virtual DbSet<LUJO_BODRUM> LUJO_BODRUM { get; set; }
        public virtual DbSet<MAXX_ROYAL_BELEK_GOLF_RESORT> MAXX_ROYAL_BELEK_GOLF_RESORT { get; set; }
        public virtual DbSet<STEIGENBERGER_ALCAZAR> STEIGENBERGER_ALCAZAR { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<VOYAGE_SORGUN> VOYAGE_SORGUN { get; set; }
    }
}
